name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
  #USER: ${{ secrets.USER}}
  #DNS: ${{secrets.DNS}}


jobs:
    taking-backup:
        runs-on: ubuntu-latest
        steps:
      
          - name: taking backup of wordpress-content
            uses: appleboy/ssh-action@v0.1.7
            with:
              host: mlgen.me
              username: nitesh
              key: ${{secrets.DEPLOY_KEY}}
              #"backup_$(date +%Y%m%d_%H%M%S)"
              script: |
                rsync -avz --delete ~/wordpress/prod/ ~/static_backup/wordpress_content_$(date +%Y%m%d_%H%M%S)/
          - name: taking backup of prod sql-database
            uses: appleboy/ssh-action@v0.1.7
            with:
              host: mlgen.me
              username: nitesh
              key: ${{secrets.DEPLOY_KEY}}
              script: |
                cd ~/wordpress
                sudo docker exec wordpress_db-prod_1 mysqldump -u'"wordpress"' -p'"wordpress"' --all-databases --skip-lock-tables > /home/nitesh/mysql_backup/mysql_backup_$(date +%Y%m%d_%H%M%S).sql
              #sudo docker-compose exec -T -e MYSQL_USER='"wordpress"' MYSQL_PASSWORD='"wordpress"' --privileged db-prod mysqldump --all-databases --skip-lock-tables > ~/mysql_backup/mysql_backup_$(date +%Y%m%d_%H%M%S).sql
            
    deploying-to-prod:
      runs-on: ubuntu-latest
      needs: [taking-backup]
      steps:
        - name: Cloning the repo
          uses: actions/checkout@v1
        - name: Authenticating
          run: |
            mkdir -p ~/.ssh
            echo "${DEPLOY_KEY}" > ~/.ssh/my_rsync_key
            echo "IdentityFile ~/.ssh/my_rsync_key" >> ~/.ssh/config
            chmod -R 700 ~/.ssh
        - name: Deploy-the-content
          run: |
            rsync -avz -e 'ssh -p 22 -i ~/.ssh/my_rsync_key -o StrictHostKeyChecking=no' --delete ./dev/ 
          #rsync -avz -e 'ssh -p 22 -i ~/.ssh/my_rsync_key -o StrictHostKeyChecking=no' --delete ./dev/ "nitesh"@"mlgen.me":~/wordpress/prod/
          #rsync -avz -e 'ssh -p 22' --delete docs/ nitesh@20.197.1.204:~/devdocs/docs
        - name: deploy-the-database
          uses: appleboy/ssh-action@v0.1.7
          with:
            host: mlgen.me
            username: nitesh
            key: ${{secrets.DEPLOY_KEY}}
            script: |
      
                cd ~/wordpress
                sudo docker stop wordpress_db-prod_1
                sudo chown -R nitesh:root ~/dev_changes/
              
                sudo docker exec wordpress_db-dev_1 mysqldump -u'"wordpress"' -p'"wordpress"' --all-databases --skip-lock-tables > ~/dev_changes/backup.sql
                sudo docker cp /home/nitesh/dev_changes/backup.sql wordpress_db-prod_1:/backup.sql
                sudo docker start wordpress_db-prod_1
                sleep 10
                sudo docker exec wordpress_db-prod_1 chmod -R 755 /db-change
                sudo docker exec wordpress_db-prod_1 chown -R root:1000 /db-change
                
              
                
                sudo docker exec wordpress_db-prod_1 sh -c "mysql -u'\"wordpress\"' -p'\"wordpress\"' < /backup.sql"

            
          
            
              