name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
  #USER: ${{ secrets.USER}}
  #DNS: ${{secrets.DNS}}

jobs:
    rsync-the-changes:
        runs-on: ubuntu-latest
        steps:
          - name: cloning the repo
            uses: actions/checkout@v1
          - name: Authenticating
            run: |
              mkdir -p ~/.ssh
              echo "${DEPLOY_KEY}" > ~/.ssh/my_rsync_key
              echo "IdentityFile ~/.ssh/my_rsync_key" >> ~/.ssh/config
              chmod -R 700 ~/.ssh
          - name: Deploy
            run: |
              ls -al
              
              rsync -avz -e 'ssh -p 22 -i ~/.ssh/my_rsync_key -o StrictHostKeyChecking=no' --delete ./dev/ "nitesh"@"mlgen.me":~/wordpress/prod/
          #rsync -avz -e 'ssh -p 22' --delete docs/ nitesh@20.197.1.204:~/devdocs/docs
            
              