name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
  #USER: ${{ secrets.USER}}
  #DNS: ${{secrets.DNS}}

jobs:
    rsync-the-changes:
        runs-on: ubuntu-latest
        steps:
      
          - name: Getting backup of wordpress-content
            uses: fifsky/ssh-action@master
            with:
              host: mlgen.me
              user: nitesh
              key: ${{secrets.DEPLOY_KEY}}
              #"backup_$(date +%Y%m%d_%H%M%S)"
              command: |
                rsync -avz ~/wordpress/dev/ ~/static_backup/wordpress_content_$(date +%Y%m%d_%H%M%S)/
          - name: Cloning the repo
            uses: actions/checkout@v1
          - name: Authenticating
            run: |
              mkdir -p ~/.ssh
              echo "${DEPLOY_KEY}" > ~/.ssh/my_rsync_key
              echo "IdentityFile ~/.ssh/my_rsync_key" >> ~/.ssh/config
              chmod -R 700 ~/.ssh
          - name: Deploy
            run: |
              ls -al
              
              rsync -avz -e 'ssh -p 22 -i ~/.ssh/my_rsync_key -o StrictHostKeyChecking=no' --delete ./dev/ "nitesh"@"mlgen.me":~/wordpress/prod/
          #rsync -avz -e 'ssh -p 22' --delete docs/ nitesh@20.197.1.204:~/devdocs/docs
            
              