name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
  #USER: ${{ secrets.USER}}
  #DNS: ${{secrets.DNS}}


jobs:
    getting-backups:
        runs-on: ubuntu-latest
        steps:
      
          - name: Getting backup of wordpress-content
            uses: appleboy/ssh-action@v0.1.7
            with:
              host: mlgen.me
              username: nitesh
              key: ${{secrets.DEPLOY_KEY}}
              #"backup_$(date +%Y%m%d_%H%M%S)"
              script: |
                rsync -avz ~/wordpress/prod/ ~/static_backup/wordpress_content_$(date +%Y%m%d_%H%M%S)/
          - name: Getting backup of prod sql-database
            uses: appleboy/ssh-action@v0.1.7
            with:
              host: mlgen.me
              username: nitesh
              key: ${{secrets.DEPLOY_KEY}}
              script: |
                cd ~/wordpress
                
                
                sudo docker-compose exec -T db-prod sh -c "mysqldump --all-databases -u 'wordpress' -p 'wordpress'" > ~/mysql_backup/mysql_backup_$(date +%Y%m%d_%H%M%S).sql
            
            
          - name: Cloning the repo
            uses: actions/checkout@v1
          - name: Authenticating
            run: |
              mkdir -p ~/.ssh
              echo "${DEPLOY_KEY}" > ~/.ssh/my_rsync_key
              echo "IdentityFile ~/.ssh/my_rsync_key" >> ~/.ssh/config
              chmod -R 700 ~/.ssh
          - name: Deploy
            run: |
              ls -al
              
              rsync -avz -e 'ssh -p 22 -i ~/.ssh/my_rsync_key -o StrictHostKeyChecking=no' --delete ./dev/ "nitesh"@"mlgen.me":~/wordpress/prod/
          #rsync -avz -e 'ssh -p 22' --delete docs/ nitesh@20.197.1.204:~/devdocs/docs
            
              